
```{r}

# Set the working directory
#############################################################################
COMP <- "MacBook" 
#COMP <- "GreatLakes"       
if(COMP == "MacBook"){
        # MacBook
        WD <- '/Volumes/Frishman_4TB/motrpac/20200915_metabolomics-pass1a'    
}else if(COMP == "GreatLakes"){
        # MichMed
        WD <- '/home/acsteep/motrpac/20200915_metabolomics-pass1a'
}
rm(COMP)


# Load dependencies
pacs...man <- c("tidyverse", "data.table","rlang","RColorBrewer","MASS","sfsmisc",
                "pheatmap","caret","ggforce","RANN","kableExtra","gtools","combinat",
                "ggrepel","ggtern","plotly","readr")
for(pac in pacs...man){
  suppressWarnings(suppressPackageStartupMessages(library(pac, character.only = TRUE)))
}

############################################################
##### Functions ############################################
############################################################

# Name functions
select <- dplyr::select
counts <- DESeq2::counts
map <- purrr::map
desc <- dplyr::desc
arrange <- dplyr::arrange
melt <- reshape2::melt
mutate <- dplyr::mutate

# Global options
options(dplyr.print_max = 100)
options(scipen=10000)

# Source the functions
source(paste0(WD,'/functions/not_in.R'))
source(paste0(WD,'/functions/rat_mouse_ortho.R'))
source(paste0(WD,'/functions/mouse2rat_ortho.R'))
source(paste0(WD,'/functions/lmp.R'))
source(paste0(WD,'/functions/cor_PC_1_6.R'))
source(paste0(WD,'/functions/elbow_finder.R'))
source(paste0(WD,'/functions/cor_outlier2.R'))
source(paste0(WD,'/functions/DissimilarityMatrixNominal.R'))
source(paste0(WD,'/functions/lm_eqn.R'))
source(paste0(WD,'/functions/reorder_cormat.R'))
source(paste0(WD,'/functions/save_pheatmap_pdf.R'))
source(paste0(WD,'/functions/modeav.R'))
source(paste0(WD,'/functions/count_na.R'))
source(paste0(WD,'/functions/se_mean.R'))
source(paste0(WD,'/functions/Mode.R'))
source(paste0(WD,'/functions/NumericSummaryStats.R'))
source(paste0(WD,'/functions/AutoScaleMatrix.R'))
source(paste0(WD,'/functions/ReverseAutoScaleMatrix.R'))
source(paste0(WD,'/functions/CenterMatrix.R'))
source(paste0(WD,'/functions/RangeScaleMatrix.R'))
source(paste0(WD,'/functions/ParetoScaleMatrix.R'))
source(paste0(WD,'/functions/VastScaleMatrix.R'))
source(paste0(WD,'/functions/LevelScaleMatrix.R'))
source(paste0(WD,'/functions/Log10Matrix.R'))
source(paste0(WD,'/functions/PowerMatrix.R'))
```

```{r}

WD <- '/Volumes/Frishman_4TB/motrpac/20200915_metabolomics-pass1a/data/'
setwd(WD)
br<-readRDS("20201103_broad-hilicpos-matrix-raw-4-jun_steep.RDS")
duke<- readRDS("20201103_duke-ac-matrix-raw-4-jun_steep.RDS")

# mismatched orders for both rows and columns

sample78 <- row.names(br) %>%
  str_remove_all('_Broad Institute_hilicpos')
feature21<-read.delim("feature21.txt",header=T,row.names=1,sep="\t")









```